package be.ucll.backend2.records_dtos.controller.dto;

/**
 * DTO for {@link be.ucll.backend2.records_dtos.model.Post}
 *
 * Fairly pointless, though, since if we would try to specify the id it
 * would just get overridden by the autogenerated id.
 */
public record CreatePostDto(String title, String content) {
}
